apiVersion: v1
kind: Service
metadata:
  labels:
    name: photoalbum-service
  name: photoalbum-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    name: photoalbum-app
  type: LoadBalancer
